# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alarmd_oc.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x0f\x61larmd_oc.proto\x1a\x13telemetry_top.proto\"\xd7\x02\n\x0csystem_alarm\x12*\n\x06\x61larms\x18\x97\x01 \x01(\x0b\x32\x19.system_alarm.alarms_type\x1a\x9a\x02\n\x0b\x61larms_type\x12\x34\n\x05\x61larm\x18\x97\x01 \x03(\x0b\x32$.system_alarm.alarms_type.alarm_list\x1a\xd4\x01\n\nalarm_list\x12\x12\n\x02id\x18\x97\x01 \x01(\tB\x05\x82@\x02\x08\x01\x12?\n\x05state\x18\x98\x01 \x01(\x0b\x32/.system_alarm.alarms_type.alarm_list.state_type\x1aq\n\nstate_type\x12\n\n\x02id\x18\x33 \x01(\t\x12\x10\n\x08resource\x18\x35 \x01(\t\x12\x0c\n\x04text\x18\x34 \x01(\t\x12\x14\n\x0ctime_created\x18\x36 \x01(\x04\x12\x10\n\x08severity\x18\x37 \x01(\t\x12\x0f\n\x07type_id\x18\x38 \x01(\t:E\n\x15jnpr_system_alarm_ext\x12\x17.JuniperNetworksSensors\x18o \x01(\x0b\x32\r.system_alarm"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

System_alarm = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_alarm").msgclass
System_alarm::Alarms_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_alarm.alarms_type").msgclass
System_alarm::Alarms_type::Alarm_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_alarm.alarms_type.alarm_list").msgclass
System_alarm::Alarms_type::Alarm_list::State_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_alarm.alarms_type.alarm_list.state_type").msgclass
