# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bbe-smgd_ancp_stats_oc.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x1c\x62\x62\x65-smgd_ancp_stats_oc.proto\x1a\x13telemetry_top.proto\"\xef\x04\n\x10junos_ancp_stats\x12.\n\x06system\x18\x97\x01 \x01(\x0b\x32\x1d.junos_ancp_stats.system_type\x1a\xaa\x04\n\x0bsystem_type\x12X\n\x15subscriber_management\x18\x97\x01 \x01(\x0b\x32\x38.junos_ancp_stats.system_type.subscriber_management_type\x1a\xc0\x03\n\x1asubscriber_management_type\x12\x65\n\x0e\x61\x63\x63\x65ss_network\x18\x97\x01 \x01(\x0b\x32L.junos_ancp_stats.system_type.subscriber_management_type.access_network_type\x1a\xba\x02\n\x13\x61\x63\x63\x65ss_network_type\x12\x65\n\x04\x61ncp\x18\x97\x01 \x01(\x0b\x32V.junos_ancp_stats.system_type.subscriber_management_type.access_network_type.ancp_type\x1a\xbb\x01\n\tancp_type\x12u\n\x07\x61\x64\x61pter\x18\x97\x01 \x01(\x0b\x32\x63.junos_ancp_stats.system_type.subscriber_management_type.access_network_type.ancp_type.adapter_type\x1a\x37\n\x0c\x61\x64\x61pter_type\x12\'\n\x1fmapped_dynamic_subscriber_count\x18\x33 \x01(\r:M\n\x19jnpr_junos_ancp_stats_ext\x12\x17.JuniperNetworksSensors\x18\" \x01(\x0b\x32\x11.junos_ancp_stats"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

Junos_ancp_stats = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_ancp_stats").msgclass
Junos_ancp_stats::System_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_ancp_stats.system_type").msgclass
Junos_ancp_stats::System_type::Subscriber_management_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_ancp_stats.system_type.subscriber_management_type").msgclass
Junos_ancp_stats::System_type::Subscriber_management_type::Access_network_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_ancp_stats.system_type.subscriber_management_type.access_network_type").msgclass
Junos_ancp_stats::System_type::Subscriber_management_type::Access_network_type::Ancp_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_ancp_stats.system_type.subscriber_management_type.access_network_type.ancp_type").msgclass
Junos_ancp_stats::System_type::Subscriber_management_type::Access_network_type::Ancp_type::Adapter_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_ancp_stats.system_type.subscriber_management_type.access_network_type.ancp_type.adapter_type").msgclass
