# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bbe-smgd_rsmon_stats_oc.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x1d\x62\x62\x65-smgd_rsmon_stats_oc.proto\x1a\x13telemetry_top.proto\"\xe7\x07\n\x11junos_rsmon_stats\x12/\n\x06system\x18\x97\x01 \x01(\x0b\x32\x1e.junos_rsmon_stats.system_type\x1a\xa0\x07\n\x0bsystem_type\x12Y\n\x15subscriber_management\x18\x97\x01 \x01(\x0b\x32\x39.junos_rsmon_stats.system_type.subscriber_management_type\x1a\xb5\x06\n\x1asubscriber_management_type\x12T\n\x05infra\x18\x97\x01 \x01(\x0b\x32\x44.junos_rsmon_stats.system_type.subscriber_management_type.infra_type\x1a\xc0\x05\n\ninfra_type\x12u\n\x10resource_monitor\x18\x97\x01 \x01(\x0b\x32Z.junos_rsmon_stats.system_type.subscriber_management_type.infra_type.resource_monitor_type\x1a\xba\x04\n\x15resource_monitor_type\x12\x81\x01\n\x0brsmon_infra\x18\x97\x01 \x01(\x0b\x32k.junos_rsmon_stats.system_type.subscriber_management_type.infra_type.resource_monitor_type.rsmon_infra_type\x1a\x9c\x03\n\x10rsmon_infra_type\x12\x84\x01\n\x04\x66pcs\x18\x97\x01 \x01(\x0b\x32u.junos_rsmon_stats.system_type.subscriber_management_type.infra_type.resource_monitor_type.rsmon_infra_type.fpcs_type\x1a\x80\x02\n\tfpcs_type\x12\x8c\x01\n\x03\x66pc\x18\x97\x01 \x03(\x0b\x32~.junos_rsmon_stats.system_type.subscriber_management_type.infra_type.resource_monitor_type.rsmon_infra_type.fpcs_type.fpc_list\x1a\x64\n\x08\x66pc_list\x12\x13\n\x04slot\x18\x33 \x01(\rB\x05\x82@\x02\x08\x01\x12!\n\x19\x64\x65lay_round_trip_exceeded\x18= \x01(\r\x12 \n\x18\x64\x65lay_round_trip_nominal\x18> \x01(\r:O\n\x1ajnpr_junos_rsmon_stats_ext\x12\x17.JuniperNetworksSensors\x18% \x01(\x0b\x32\x12.junos_rsmon_stats"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

Junos_rsmon_stats = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_rsmon_stats").msgclass
Junos_rsmon_stats::System_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_rsmon_stats.system_type").msgclass
Junos_rsmon_stats::System_type::Subscriber_management_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_rsmon_stats.system_type.subscriber_management_type").msgclass
Junos_rsmon_stats::System_type::Subscriber_management_type::Infra_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_rsmon_stats.system_type.subscriber_management_type.infra_type").msgclass
Junos_rsmon_stats::System_type::Subscriber_management_type::Infra_type::Resource_monitor_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_rsmon_stats.system_type.subscriber_management_type.infra_type.resource_monitor_type").msgclass
Junos_rsmon_stats::System_type::Subscriber_management_type::Infra_type::Resource_monitor_type::Rsmon_infra_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_rsmon_stats.system_type.subscriber_management_type.infra_type.resource_monitor_type.rsmon_infra_type").msgclass
Junos_rsmon_stats::System_type::Subscriber_management_type::Infra_type::Resource_monitor_type::Rsmon_infra_type::Fpcs_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_rsmon_stats.system_type.subscriber_management_type.infra_type.resource_monitor_type.rsmon_infra_type.fpcs_type").msgclass
Junos_rsmon_stats::System_type::Subscriber_management_type::Infra_type::Resource_monitor_type::Rsmon_infra_type::Fpcs_type::Fpc_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_rsmon_stats.system_type.subscriber_management_type.infra_type.resource_monitor_type.rsmon_infra_type.fpcs_type.fpc_list").msgclass
