# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chassisd_interfaces_oc.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x1c\x63hassisd_interfaces_oc.proto\x1a\x13telemetry_top.proto\"\x88\x02\n\x12interfaces_chassis\x12\x35\n\tinterface\x18\x38 \x03(\x0b\x32\".interfaces_chassis.interface_list\x1a\xba\x01\n\x0einterface_list\x12\x13\n\x04name\x18\x33 \x01(\tB\x05\x82@\x02\x08\x01\x12<\n\x05state\x18= \x01(\x0b\x32-.interfaces_chassis.interface_list.state_type\x1aU\n\nstate_type\x12\x16\n\rhardware_port\x18\x99\x01 \x01(\t\x12\x14\n\x0btransceiver\x18\x9a\x01 \x01(\t\x12\x19\n\x10physical_channel\x18\x9b\x01 \x01(\r:Q\n\x1bjnpr_interfaces_chassis_ext\x12\x17.JuniperNetworksSensors\x18m \x01(\x0b\x32\x13.interfaces_chassis"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

Interfaces_chassis = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_chassis").msgclass
Interfaces_chassis::Interface_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_chassis.interface_list").msgclass
Interfaces_chassis::Interface_list::State_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_chassis.interface_list.state_type").msgclass
