# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cpu_memory_utilization.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x1c\x63pu_memory_utilization.proto\x1a\x13telemetry_top.proto\"I\n\x14\x43puMemoryUtilization\x12\x31\n\x0butilization\x18\x01 \x03(\x0b\x32\x1c.CpuMemoryUtilizationSummary\"\xad\x01\n\x1b\x43puMemoryUtilizationSummary\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x04\x12\x17\n\x0f\x62ytes_allocated\x18\x03 \x01(\x04\x12\x13\n\x0butilization\x18\x04 \x01(\x05\x12\x44\n\x17\x61pplication_utilization\x18\x05 \x03(\x0b\x32#.CpuMemoryUtilizationPerApplication\"\x8b\x01\n\"CpuMemoryUtilizationPerApplication\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x0f\x62ytes_allocated\x18\x02 \x01(\x04\x12\x13\n\x0b\x61llocations\x18\x03 \x01(\x04\x12\r\n\x05\x66rees\x18\x04 \x01(\x04\x12\x1a\n\x12\x61llocations_failed\x18\x05 \x01(\x04:K\n\x13\x63pu_memory_util_ext\x12\x17.JuniperNetworksSensors\x18\x01 \x01(\x0b\x32\x15.CpuMemoryUtilization"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

CpuMemoryUtilization = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CpuMemoryUtilization").msgclass
CpuMemoryUtilizationSummary = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CpuMemoryUtilizationSummary").msgclass
CpuMemoryUtilizationPerApplication = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CpuMemoryUtilizationPerApplication").msgclass
