# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eventd.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x0c\x65ventd.proto\x1a\x13telemetry_top.proto\"\xb4\x04\n\x0cjunos_events\x12*\n\x06\x65vents\x18\x97\x01 \x01(\x0b\x32\x19.junos_events.events_type\x1a\xf7\x03\n\x0b\x65vents_type\x12\x34\n\x05\x65vent\x18\x97\x01 \x03(\x0b\x32$.junos_events.events_type.event_list\x1a\xb1\x03\n\nevent_list\x12\n\n\x02id\x18\x33 \x01(\t\x12\x0c\n\x04type\x18\x34 \x01(\t\x12G\n\ttimestamp\x18\x97\x01 \x01(\x0b\x32\x33.junos_events.events_type.event_list.timestamp_type\x12\x10\n\x08priority\x18\x35 \x01(\t\x12\x10\n\x08\x66\x61\x63ility\x18\x36 \x01(\t\x12\x0b\n\x03pid\x18\x37 \x01(\r\x12\x0f\n\x07message\x18\x38 \x01(\t\x12\x0e\n\x06\x64\x61\x65mon\x18\x39 \x01(\t\x12\x10\n\x08hostname\x18: \x01(\t\x12\x0e\n\x06lsname\x18; \x01(\t\x12I\n\nattributes\x18\x98\x01 \x03(\x0b\x32\x34.junos_events.events_type.event_list.attributes_list\x12\x12\n\nlogoptions\x18< \x01(\x05\x1a\x37\n\x0etimestamp_type\x12\x0f\n\x07seconds\x18\x33 \x01(\r\x12\x14\n\x0cmicroseconds\x18\x34 \x01(\r\x1a\x34\n\x0f\x61ttributes_list\x12\x12\n\x03key\x18\x33 \x01(\tB\x05\x82@\x02\x08\x01\x12\r\n\x05value\x18\x34 \x01(\t:E\n\x15jnpr_junos_events_ext\x12\x17.JuniperNetworksSensors\x18* \x01(\x0b\x32\r.junos_events"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

Junos_events = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_events").msgclass
Junos_events::Events_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_events.events_type").msgclass
Junos_events::Events_type::Event_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_events.events_type.event_list").msgclass
Junos_events::Events_type::Event_list::Timestamp_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_events.events_type.event_list.timestamp_type").msgclass
Junos_events::Events_type::Event_list::Attributes_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_events.events_type.event_list.attributes_list").msgclass
