# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fpc_environment.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x15\x66pc_environment.proto\x1a\x13telemetry_top.proto\"I\n\x0bg_temp_info\x12\x1f\n\x10temp_sensor_name\x18\x01 \x02(\tB\x05\x82@\x02\x08\x01\x12\x19\n\ntemp_value\x18\x02 \x02(\x05\x42\x05\x82@\x02 \x01\"R\n\x0eg_voltage_info\x12\"\n\x13voltage_sensor_name\x18\x01 \x02(\tB\x05\x82@\x02\x08\x01\x12\x1c\n\rvoltage_value\x18\x02 \x02(\x05\x42\x05\x82@\x02 \x01\"8\n\x0cg_power_info\x12\x15\n\rmax_fpc_power\x18\x01 \x01(\x05\x12\x11\n\tfpc_power\x18\x02 \x01(\x05\"\xd0\x02\n\x11g_fpc_environment\x12#\n\x0cpower_record\x18\x01 \x01(\x0b\x32\r.g_power_info\x12!\n\x0btemp_record\x18\x02 \x03(\x0b\x32\x0c.g_temp_info\x12\'\n\x0evoltage_record\x18\x03 \x03(\x0b\x32\x0f.g_voltage_info\x12\x32\n\x08linecard\x18\x04 \x03(\x0b\x32 .g_fpc_environment.linecard_list\x1a\x95\x01\n\rlinecard_list\x12\x13\n\x04name\x18\x04 \x01(\tB\x05\x82@\x02\x08\x01\x12#\n\x0cpower_record\x18\x01 \x01(\x0b\x32\r.g_power_info\x12!\n\x0btemp_record\x18\x02 \x03(\x0b\x32\x0c.g_temp_info\x12\'\n\x0evoltage_record\x18\x03 \x03(\x0b\x32\x0f.g_voltage_info:F\n\x11\x66pcEnvironmentExt\x12\x17.JuniperNetworksSensors\x18\x04 \x01(\x0b\x32\x12.g_fpc_environment"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

G_temp_info = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g_temp_info").msgclass
G_voltage_info = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g_voltage_info").msgclass
G_power_info = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g_power_info").msgclass
G_fpc_environment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g_fpc_environment").msgclass
G_fpc_environment::Linecard_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("g_fpc_environment.linecard_list").msgclass
