# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GnmiJuniperTelemetryHeaderExtension.proto

require 'google/protobuf'


descriptor_data = "\n)GnmiJuniperTelemetryHeaderExtension.proto\"\xbd\x03\n#GnmiJuniperTelemetryHeaderExtension\x12\x11\n\tsystem_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63omponent_id\x18\x02 \x01(\r\x12\x18\n\x10sub_component_id\x18\x03 \x01(\r\x12\x13\n\x0bsensor_name\x18\x04 \x01(\t\x12\x17\n\x0fsubscribed_path\x18\x05 \x01(\t\x12\x15\n\rstreamed_path\x18\x06 \x01(\t\x12\x11\n\tcomponent\x18\x07 \x01(\t\x12\x17\n\x0fsequence_number\x18\x08 \x01(\x04\x12\x1d\n\x15payload_get_timestamp\x18\t \x01(\x03\x12!\n\x19stream_creation_timestamp\x18\n \x01(\x03\x12\x1b\n\x0f\x65vent_timestamp\x18\x0b \x01(\x03\x42\x02\x18\x01\x12\x18\n\x10\x65xport_timestamp\x18\x0c \x01(\x03\x12\x1b\n\x13sub_sequence_number\x18\r \x01(\x04\x12\x0b\n\x03\x65om\x18\x0e \x01(\x08\x12\x1f\n\x17\x65vent_publish_timestamp\x18\x0f \x01(\x03\x12\x1e\n\tstream_id\x18\x10 \x01(\x0e\x32\x0b.StreamType*:\n\nStreamType\x12\x10\n\x0cINITIAL_SYNC\x10\x00\x12\x0c\n\x08ONCHANGE\x10\x01\x12\x0c\n\x08PERIODIC\x10\x02\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

GnmiJuniperTelemetryHeaderExtension = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("GnmiJuniperTelemetryHeaderExtension").msgclass
StreamType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StreamType").enummodule
