# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gnmi_ext.proto

require 'google/protobuf'


descriptor_data = "\n\x0egnmi_ext.proto\x12\x08gnmi_ext\"\x86\x01\n\tExtension\x12\x37\n\x0eregistered_ext\x18\x01 \x01(\x0b\x32\x1d.gnmi_ext.RegisteredExtensionH\x00\x12\x39\n\x12master_arbitration\x18\x02 \x01(\x0b\x32\x1b.gnmi_ext.MasterArbitrationH\x00\x42\x05\n\x03\x65xt\"E\n\x13RegisteredExtension\x12!\n\x02id\x18\x01 \x01(\x0e\x32\x15.gnmi_ext.ExtensionID\x12\x0b\n\x03msg\x18\x02 \x01(\x0c\"Y\n\x11MasterArbitration\x12\x1c\n\x04role\x18\x01 \x01(\x0b\x32\x0e.gnmi_ext.Role\x12&\n\x0b\x65lection_id\x18\x02 \x01(\x0b\x32\x11.gnmi_ext.Uint128\"$\n\x07Uint128\x12\x0c\n\x04high\x18\x01 \x01(\x04\x12\x0b\n\x03low\x18\x02 \x01(\x04\"\x12\n\x04Role\x12\n\n\x02id\x18\x01 \x01(\t*U\n\x0b\x45xtensionID\x12\r\n\tEID_UNSET\x10\x00\x12 \n\x1c\x45ID_JUNIPER_TELEMETRY_HEADER\x10\x01\x12\x15\n\x10\x45ID_EXPERIMENTAL\x10\xe7\x07\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module GnmiExt
  Extension = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gnmi_ext.Extension").msgclass
  RegisteredExtension = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gnmi_ext.RegisteredExtension").msgclass
  MasterArbitration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gnmi_ext.MasterArbitration").msgclass
  Uint128 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gnmi_ext.Uint128").msgclass
  Role = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gnmi_ext.Role").msgclass
  ExtensionID = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gnmi_ext.ExtensionID").enummodule
end
