# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jkdsd_oc.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x0ejkdsd_oc.proto\x1a\x13telemetry_top.proto\"\xc6\x03\n\x0csystem_debug\x12\x30\n\tprocesses\x18\x97\x01 \x01(\x0b\x32\x1c.system_debug.processes_type\x1a\x83\x03\n\x0eprocesses_type\x12;\n\x07process\x18\x97\x01 \x03(\x0b\x32).system_debug.processes_type.process_list\x1a\xb3\x02\n\x0cprocess_list\x12\x12\n\x03pid\x18\x33 \x01(\x04\x42\x05\x82@\x02\x08\x01\x12\x44\n\x05state\x18\x97\x01 \x01(\x0b\x32\x34.system_debug.processes_type.process_list.state_type\x1a\xc8\x01\n\nstate_type\x12\x0b\n\x03pid\x18\x33 \x01(\x04\x12\x0c\n\x04name\x18\x34 \x01(\t\x12\x12\n\nstart_time\x18\x35 \x01(\x04\x12\x0e\n\x06uptime\x18\x36 \x01(\x04\x12\x16\n\x0e\x63pu_usage_user\x18\x37 \x01(\x04\x12\x18\n\x10\x63pu_usage_system\x18\x38 \x01(\x04\x12\x17\n\x0f\x63pu_utilization\x18\x39 \x01(\r\x12\x14\n\x0cmemory_usage\x18: \x01(\x04\x12\x1a\n\x12memory_utilization\x18; \x01(\r:E\n\x15jnpr_system_debug_ext\x12\x17.JuniperNetworksSensors\x18j \x01(\x0b\x32\r.system_debug"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

System_debug = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_debug").msgclass
System_debug::Processes_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_debug.processes_type").msgclass
System_debug::Processes_type::Process_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_debug.processes_type.process_list").msgclass
System_debug::Processes_type::Process_list::State_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_debug.processes_type.process_list.state_type").msgclass
