# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jkdsd_cpu_oc.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x12jkdsd_cpu_oc.proto\x1a\x13telemetry_top.proto\"\xf0\x03\n\x10\x63omponents_debug\x12\x34\n\tcomponent\x18\x97\x01 \x03(\x0b\x32 .components_debug.component_list\x1a\xa5\x03\n\x0e\x63omponent_list\x12\x13\n\x04name\x18\x33 \x01(\tB\x05\x82@\x02\x08\x01\x12\x37\n\x03\x63pu\x18\x97\x01 \x01(\x0b\x32).components_debug.component_list.cpu_type\x1a\xc4\x02\n\x08\x63pu_type\x12P\n\x0butilization\x18\x97\x01 \x01(\x0b\x32:.components_debug.component_list.cpu_type.utilization_type\x1a\xe5\x01\n\x10utilization_type\x12U\n\x05state\x18\x97\x01 \x01(\x0b\x32\x45.components_debug.component_list.cpu_type.utilization_type.state_type\x1az\n\nstate_type\x12\x0f\n\x07instant\x18\x34 \x01(\r\x12\x0b\n\x03\x61vg\x18\x35 \x01(\r\x12\x0b\n\x03min\x18\x36 \x01(\r\x12\x0b\n\x03max\x18\x37 \x01(\r\x12\x10\n\x08interval\x18\x38 \x01(\x04\x12\x10\n\x08min_time\x18\x39 \x01(\x04\x12\x10\n\x08max_time\x18: \x01(\x04:M\n\x19jnpr_components_debug_ext\x12\x17.JuniperNetworksSensors\x18k \x01(\x0b\x32\x11.components_debug"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

Components_debug = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("components_debug").msgclass
Components_debug::Component_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("components_debug.component_list").msgclass
Components_debug::Component_list::Cpu_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("components_debug.component_list.cpu_type").msgclass
Components_debug::Component_list::Cpu_type::Utilization_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("components_debug.component_list.cpu_type.utilization_type").msgclass
Components_debug::Component_list::Cpu_type::Utilization_type::State_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("components_debug.component_list.cpu_type.utilization_type.state_type").msgclass
