# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jl2tpd_oc.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x0fjl2tpd_oc.proto\x1a\x13telemetry_top.proto\"\x9d\x08\n\njunos_l2tp\x12(\n\x06system\x18\x97\x01 \x01(\x0b\x32\x17.junos_l2tp.system_type\x1a\xe4\x07\n\x0bsystem_type\x12R\n\x15subscriber_management\x18\x97\x01 \x01(\x0b\x32\x32.junos_l2tp.system_type.subscriber_management_type\x1a\x80\x07\n\x1asubscriber_management_type\x12\x63\n\x10\x63lient_protocols\x18\x97\x01 \x01(\x0b\x32H.junos_l2tp.system_type.subscriber_management_type.client_protocols_type\x1a\xfc\x05\n\x15\x63lient_protocols_type\x12\x61\n\x04l2tp\x18\x97\x01 \x01(\x0b\x32R.junos_l2tp.system_type.subscriber_management_type.client_protocols_type.l2tp_type\x1a\xff\x04\n\tl2tp_type\x12q\n\x07summary\x18\x97\x01 \x01(\x0b\x32_.junos_l2tp.system_type.subscriber_management_type.client_protocols_type.l2tp_type.summary_type\x1a\xfe\x03\n\x0csummary_type\x12 \n\x18l2tp_stats_total_tunnels\x18\x33 \x01(\r\x12!\n\x19l2tp_stats_total_sessions\x18\x34 \x01(\r\x12%\n\x1dl2tp_stats_control_rx_packets\x18\x35 \x01(\r\x12#\n\x1bl2tp_stats_control_rx_bytes\x18\x36 \x01(\r\x12%\n\x1dl2tp_stats_control_tx_packets\x18\x37 \x01(\r\x12#\n\x1bl2tp_stats_control_tx_bytes\x18\x38 \x01(\r\x12)\n!l2tp_era_type_icrq_inflight_count\x18\x39 \x01(\r\x12-\n%l2tp_era_type_icrq_reported_successes\x18: \x01(\r\x12,\n$l2tp_era_type_icrq_reported_failures\x18; \x01(\r\x12*\n\"l2tp_era_type_sccrq_inflight_count\x18< \x01(\r\x12.\n&l2tp_era_type_sccrq_reported_successes\x18= \x01(\r\x12-\n%l2tp_era_type_sccrq_reported_failures\x18> \x01(\r:A\n\x13jnpr_junos_l2tp_ext\x12\x17.JuniperNetworksSensors\x18, \x01(\x0b\x32\x0b.junos_l2tp"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

Junos_l2tp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_l2tp").msgclass
Junos_l2tp::System_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_l2tp.system_type").msgclass
Junos_l2tp::System_type::Subscriber_management_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_l2tp.system_type.subscriber_management_type").msgclass
Junos_l2tp::System_type::Subscriber_management_type::Client_protocols_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_l2tp.system_type.subscriber_management_type.client_protocols_type").msgclass
Junos_l2tp::System_type::Subscriber_management_type::Client_protocols_type::L2tp_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_l2tp.system_type.subscriber_management_type.client_protocols_type.l2tp_type").msgclass
Junos_l2tp::System_type::Subscriber_management_type::Client_protocols_type::L2tp_type::Summary_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_l2tp.system_type.subscriber_management_type.client_protocols_type.l2tp_type.summary_type").msgclass
