# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jpppd_oc.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x0ejpppd_oc.proto\x1a\x13telemetry_top.proto\"\x88\x06\n\tjunos_ppp\x12\'\n\x06system\x18\x97\x01 \x01(\x0b\x32\x16.junos_ppp.system_type\x1a\xd1\x05\n\x0bsystem_type\x12Q\n\x15subscriber_management\x18\x97\x01 \x01(\x0b\x32\x31.junos_ppp.system_type.subscriber_management_type\x1a\xee\x04\n\x1asubscriber_management_type\x12\x62\n\x10\x63lient_protocols\x18\x97\x01 \x01(\x0b\x32G.junos_ppp.system_type.subscriber_management_type.client_protocols_type\x1a\xeb\x03\n\x15\x63lient_protocols_type\x12^\n\x03ppp\x18\x97\x01 \x01(\x0b\x32P.junos_ppp.system_type.subscriber_management_type.client_protocols_type.ppp_type\x1a\xf1\x02\n\x08ppp_type\x12u\n\nstatistics\x18\x97\x01 \x01(\x0b\x32`.junos_ppp.system_type.subscriber_management_type.client_protocols_type.ppp_type.statistics_type\x1a\xed\x01\n\x0fstatistics_type\x12+\n#ppp_stats_total_subscriber_sessions\x18\x33 \x01(\r\x12(\n ppp_stats_sessions_disable_phase\x18\x34 \x01(\r\x12*\n\"ppp_stats_sessions_establish_phase\x18\x35 \x01(\r\x12(\n ppp_stats_sessions_network_phase\x18\x36 \x01(\r\x12-\n%ppp_stats_sessions_authenticate_phase\x18\x37 \x01(\r:?\n\x12jnpr_junos_ppp_ext\x12\x17.JuniperNetworksSensors\x18- \x01(\x0b\x32\n.junos_ppp"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

Junos_ppp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_ppp").msgclass
Junos_ppp::System_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_ppp.system_type").msgclass
Junos_ppp::System_type::Subscriber_management_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_ppp.system_type.subscriber_management_type").msgclass
Junos_ppp::System_type::Subscriber_management_type::Client_protocols_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_ppp.system_type.subscriber_management_type.client_protocols_type").msgclass
Junos_ppp::System_type::Subscriber_management_type::Client_protocols_type::Ppp_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_ppp.system_type.subscriber_management_type.client_protocols_type.ppp_type").msgclass
Junos_ppp::System_type::Subscriber_management_type::Client_protocols_type::Ppp_type::Statistics_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_ppp.system_type.subscriber_management_type.client_protocols_type.ppp_type.statistics_type").msgclass
