# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: l2ald_bd_render.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x15l2ald_bd_render.proto\x1a\x13telemetry_top.proto\"\xbc\x04\n\x1fnetwork_instances_bridge_domain\x12Q\n\x10network_instance\x18\x97\x01 \x03(\x0b\x32\x36.network_instances_bridge_domain.network_instance_list\x1a\xc5\x03\n\x15network_instance_list\x12\x13\n\x04name\x18\x33 \x01(\tB\x05\x82@\x02\x08\x01\x12O\n\x04vlan\x18\x97\x01 \x03(\x0b\x32@.network_instances_bridge_domain.network_instance_list.vlan_list\x1a\xc5\x02\n\tvlan_list\x12\x18\n\tvlan_name\x18\x33 \x01(\tB\x05\x82@\x02\x08\x01\x12\x0f\n\x07vlan_id\x18\x34 \x01(\r\x12\x0e\n\x06status\x18\x35 \x01(\t\x12\x0b\n\x03vni\x18\x36 \x01(\r\x12\x14\n\x0cl3_interface\x18\x37 \x01(\t\x12\x1d\n\x15num_local_mac_entries\x18\x38 \x01(\r\x12!\n\x19num_ar_replicator_entries\x18\x39 \x01(\r\x12\x17\n\x0f\x65thernet_tag_id\x18: \x01(\r\x12]\n\x06member\x18\xa1\x01 \x03(\x0b\x32L.network_instances_bridge_domain.network_instance_list.vlan_list.member_list\x1a \n\x0bmember_list\x12\x11\n\tinterface\x18= \x01(\t:k\n(jnpr_network_instances_bridge_domain_ext\x12\x17.JuniperNetworksSensors\x18s \x01(\x0b\x32 .network_instances_bridge_domain"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

Network_instances_bridge_domain = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("network_instances_bridge_domain").msgclass
Network_instances_bridge_domain::Network_instance_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("network_instances_bridge_domain.network_instance_list").msgclass
Network_instances_bridge_domain::Network_instance_list::Vlan_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("network_instances_bridge_domain.network_instance_list.vlan_list").msgclass
Network_instances_bridge_domain::Network_instance_list::Vlan_list::Member_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("network_instances_bridge_domain.network_instance_list.vlan_list.member_list").msgclass
