# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ldp_p2mp_per_if_egress.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x1cldp_p2mp_per_if_egress.proto\x1a\x13telemetry_top.proto\"E\n\x12LdpP2mpPerIfEgress\x12/\n\x0eper_if_records\x18\x01 \x03(\x0b\x32\x17.LdpP2mpInterfaceRecord\"\xc8\x01\n\x16LdpP2mpInterfaceRecord\x12\x16\n\x07if_name\x18\x01 \x02(\tB\x05\x82@\x02\x08\x01\x12\x1b\n\x0c\x63ounter_name\x18\x02 \x01(\tB\x05\x82@\x02\x08\x01\x12<\n\ringress_stats\x18\x03 \x01(\x0b\x32%.LabelDistributionProtocolP2mpIfStats\x12;\n\x0c\x65gress_stats\x18\x04 \x01(\x0b\x32%.LabelDistributionProtocolP2mpIfStats\"\x8a\x01\n$LabelDistributionProtocolP2mpIfStats\x12\x16\n\x07packets\x18\x01 \x01(\x04\x42\x05\x82@\x02\x18\x01\x12\x14\n\x05\x62ytes\x18\x02 \x01(\x04\x42\x05\x82@\x02\x18\x01\x12\x1a\n\x0bpacket_rate\x18\x03 \x01(\x04\x42\x05\x82@\x02 \x01\x12\x18\n\tbyte_rate\x18\x04 \x01(\x04\x42\x05\x82@\x02 \x01:V\n\x1fjnpr_ldp_p2mp_per_if_egress_ext\x12\x17.JuniperNetworksSensors\x18\x9c\x01 \x01(\x0b\x32\x13.LdpP2mpPerIfEgress"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

LdpP2mpPerIfEgress = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LdpP2mpPerIfEgress").msgclass
LdpP2mpInterfaceRecord = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LdpP2mpInterfaceRecord").msgclass
LabelDistributionProtocolP2mpIfStats = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("LabelDistributionProtocolP2mpIfStats").msgclass
