# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license-check-features-oc.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x1flicense-check-features-oc.proto\x1a\x13telemetry_top.proto\"\x95\x04\n\x0esystem_license\x12.\n\x07license\x18\x97\x01 \x01(\x0b\x32\x1c.system_license.license_type\x1a\xd2\x03\n\x0clicense_type\x12=\n\x08licenses\x18\x97\x01 \x01(\x0b\x32*.system_license.license_type.licenses_type\x1a\x82\x03\n\rlicenses_type\x12I\n\x07license\x18\x97\x01 \x03(\x0b\x32\x37.system_license.license_type.licenses_type.license_list\x1a\xa5\x02\n\x0clicense_list\x12\x1a\n\nlicense_id\x18\x97\x01 \x01(\tB\x05\x82@\x02\x08\x01\x12R\n\x05state\x18\x98\x01 \x01(\x0b\x32\x42.system_license.license_type.licenses_type.license_list.state_type\x1a\xa4\x01\n\nstate_type\x12\x12\n\nlicense_id\x18\x33 \x01(\t\x12\x14\n\x0clicense_data\x18\x34 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x35 \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\x36 \x01(\t\x12\x17\n\x0f\x65xpiration_date\x18\x37 \x01(\x04\x12\x0e\n\x06in_use\x18\x38 \x01(\x08\x12\x0f\n\x07\x65xpired\x18\x39 \x01(\x08\x12\r\n\x05valid\x18: \x01(\x08:I\n\x17jnpr_system_license_ext\x12\x17.JuniperNetworksSensors\x18l \x01(\x0b\x32\x0f.system_license"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

System_license = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_license").msgclass
System_license::License_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_license.license_type").msgclass
System_license::License_type::Licenses_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_license.license_type.licenses_type").msgclass
System_license::License_type::Licenses_type::License_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_license.license_type.licenses_type.license_list").msgclass
System_license::License_type::Licenses_type::License_list::State_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_license.license_type.licenses_type.license_list.state_type").msgclass
