# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: npu_memory_utilization.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x1cnpu_memory_utilization.proto\x1a\x13telemetry_top.proto\"E\n!NetworkProcessorMemoryUtilization\x12 \n\x0cmemory_stats\x18\x01 \x03(\x0b\x32\n.NpuMemory\"k\n\tNpuMemory\x12\x12\n\nidentifier\x18\x01 \x02(\t\x12\"\n\x07summary\x18\x02 \x03(\x0b\x32\x11.NpuMemorySummary\x12&\n\tpartition\x18\x03 \x03(\x0b\x32\x13.NpuMemoryPartition\"_\n\x10NpuMemorySummary\x12\x15\n\rresource_name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x04\x12\x11\n\tallocated\x18\x03 \x01(\x04\x12\x13\n\x0butilization\x18\x04 \x01(\x05\"\x83\x01\n\x12NpuMemoryPartition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x10\x61pplication_name\x18\x02 \x01(\t\x12\x17\n\x0f\x62ytes_allocated\x18\x03 \x01(\r\x12\x18\n\x10\x61llocation_count\x18\x04 \x01(\r\x12\x12\n\nfree_count\x18\x05 \x01(\r:S\n\x0enpu_memory_ext\x12\x17.JuniperNetworksSensors\x18\x0b \x01(\x0b\x32\".NetworkProcessorMemoryUtilization"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

NetworkProcessorMemoryUtilization = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NetworkProcessorMemoryUtilization").msgclass
NpuMemory = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NpuMemory").msgclass
NpuMemorySummary = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NpuMemorySummary").msgclass
NpuMemoryPartition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NpuMemoryPartition").msgclass
