# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packet_stats.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x12packet_stats.proto\x1a\x13telemetry_top.proto\"y\n\x10PacketStatistics\x12\'\n\x0cpacket_stats\x18\x01 \x03(\x0b\x32\x11.PacketStatsClass\x12<\n\x10packet_stats_pfe\x18\x02 \x03(\x0b\x32\".PacketStatsPacketForwardingEngine\"d\n!PacketStatsPacketForwardingEngine\x12\x16\n\x0epfe_identifier\x18\x01 \x02(\t\x12\'\n\x0cpacket_stats\x18\x02 \x03(\x0b\x32\x11.PacketStatsClass\"F\n\x10PacketStatsClass\x12\x0c\n\x04name\x18\x01 \x02(\t\x12$\n\x07\x63ounter\x18\x02 \x02(\x0b\x32\x13.PacketStatsCounter\"e\n\x12PacketStatsCounter\x12\x14\n\x0cpacket_count\x18\x01 \x02(\x04\x12\x12\n\nbyte_count\x18\x02 \x01(\x04\x12\x13\n\x0bpacket_rate\x18\x03 \x01(\x04\x12\x10\n\x08\x62it_rate\x18\x04 \x01(\x04:N\n\x1ajnpr_packet_statistics_ext\x12\x17.JuniperNetworksSensors\x18\x08 \x01(\x0b\x32\x11.PacketStatistics"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

PacketStatistics = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PacketStatistics").msgclass
PacketStatsPacketForwardingEngine = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PacketStatsPacketForwardingEngine").msgclass
PacketStatsClass = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PacketStatsClass").msgclass
PacketStatsCounter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PacketStatsCounter").msgclass
