# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pfe_ifl_family_v4_stats_oc.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n pfe_ifl_family_v4_stats_oc.proto\x1a\x13telemetry_top.proto\"\xe7\x07\n\x1cinterfaces_pfe_ifl_family_v4\x12@\n\tinterface\x18\x97\x01 \x03(\x0b\x32,.interfaces_pfe_ifl_family_v4.interface_list\x1a\x84\x07\n\x0einterface_list\x12\x13\n\x04name\x18\x33 \x01(\tB\x05\x82@\x02\x08\x01\x12W\n\rsubinterfaces\x18\x97\x01 \x01(\x0b\x32?.interfaces_pfe_ifl_family_v4.interface_list.subinterfaces_type\x1a\x83\x06\n\x12subinterfaces_type\x12h\n\x0csubinterface\x18\x97\x01 \x03(\x0b\x32Q.interfaces_pfe_ifl_family_v4.interface_list.subinterfaces_type.subinterface_list\x1a\x82\x05\n\x11subinterface_list\x12\x14\n\x05index\x18\x33 \x01(\rB\x05\x82@\x02\x08\x01\x12j\n\x04ipv4\x18\x97\x01 \x01(\x0b\x32[.interfaces_pfe_ifl_family_v4.interface_list.subinterfaces_type.subinterface_list.ipv4_type\x1a\xea\x03\n\tipv4_type\x12v\n\x05state\x18\x97\x01 \x01(\x0b\x32\x66.interfaces_pfe_ifl_family_v4.interface_list.subinterfaces_type.subinterface_list.ipv4_type.state_type\x1a\xe4\x02\n\nstate_type\x12\x87\x01\n\x08\x63ounters\x18\x97\x01 \x01(\x0b\x32t.interfaces_pfe_ifl_family_v4.interface_list.subinterfaces_type.subinterface_list.ipv4_type.state_type.counters_type\x1a\xcb\x01\n\rcounters_type\x12\x0f\n\x07in_pkts\x18\x33 \x01(\x04\x12\x11\n\tin_octets\x18\x34 \x01(\x04\x12\x19\n\x11in_multicast_pkts\x18\x35 \x01(\x04\x12\x1b\n\x13in_multicast_octets\x18\x36 \x01(\x04\x12\x10\n\x08out_pkts\x18\x37 \x01(\x04\x12\x12\n\nout_octets\x18\x38 \x01(\x04\x12\x1a\n\x12out_multicast_pkts\x18\x39 \x01(\x04\x12\x1c\n\x14out_multicast_octets\x18: \x01(\x04:f\n%jnpr_interfaces_pfe_ifl_family_v4_ext\x12\x17.JuniperNetworksSensors\x18\x87\x01 \x01(\x0b\x32\x1d.interfaces_pfe_ifl_family_v4"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

Interfaces_pfe_ifl_family_v4 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_pfe_ifl_family_v4").msgclass
Interfaces_pfe_ifl_family_v4::Interface_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_pfe_ifl_family_v4.interface_list").msgclass
Interfaces_pfe_ifl_family_v4::Interface_list::Subinterfaces_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_pfe_ifl_family_v4.interface_list.subinterfaces_type").msgclass
Interfaces_pfe_ifl_family_v4::Interface_list::Subinterfaces_type::Subinterface_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_pfe_ifl_family_v4.interface_list.subinterfaces_type.subinterface_list").msgclass
Interfaces_pfe_ifl_family_v4::Interface_list::Subinterfaces_type::Subinterface_list::Ipv4_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_pfe_ifl_family_v4.interface_list.subinterfaces_type.subinterface_list.ipv4_type").msgclass
Interfaces_pfe_ifl_family_v4::Interface_list::Subinterfaces_type::Subinterface_list::Ipv4_type::State_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_pfe_ifl_family_v4.interface_list.subinterfaces_type.subinterface_list.ipv4_type.state_type").msgclass
Interfaces_pfe_ifl_family_v4::Interface_list::Subinterfaces_type::Subinterface_list::Ipv4_type::State_type::Counters_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_pfe_ifl_family_v4.interface_list.subinterfaces_type.subinterface_list.ipv4_type.state_type.counters_type").msgclass
