# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pfe_page_drop_oc.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x16pfe_page_drop_oc.proto\x1a\x13telemetry_top.proto\"\xc2\x03\n\tjunos_228\x12\'\n\x06system\x18\x97\x01 \x01(\x0b\x32\x16.junos_228.system_type\x1a\x8b\x03\n\x0bsystem_type\x12\x37\n\x08linecard\x18\x97\x01 \x01(\x0b\x32$.junos_228.system_type.linecard_type\x1a\xc2\x02\n\rlinecard_type\x12I\n\npage_drops\x18\x97\x01 \x01(\x0b\x32\x34.junos_228.system_type.linecard_type.page_drops_type\x1a\xe5\x01\n\x0fpage_drops_type\x12W\n\tpage_drop\x18\x98\x01 \x03(\x0b\x32\x43.junos_228.system_type.linecard_type.page_drops_type.page_drop_list\x1ay\n\x0epage_drop_list\x12\x12\n\x03pfe\x18\x33 \x01(\rB\x05\x82@\x02\x08\x01\x12\r\n\x05\x63ount\x18\x34 \x01(\r\x12\x11\n\tinterface\x18\x35 \x01(\t\x12\x14\n\x0cinterface_oq\x18\x36 \x01(\r\x12\x1b\n\x13interface_parent_ae\x18\x37 \x01(\t:@\n\x12jnpr_junos_228_ext\x12\x17.JuniperNetworksSensors\x18\xe4\x01 \x01(\x0b\x32\n.junos_228"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

Junos_228 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_228").msgclass
Junos_228::System_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_228.system_type").msgclass
Junos_228::System_type::Linecard_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_228.system_type.linecard_type").msgclass
Junos_228::System_type::Linecard_type::Page_drops_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_228.system_type.linecard_type.page_drops_type").msgclass
Junos_228::System_type::Linecard_type::Page_drops_type::Page_drop_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_228.system_type.linecard_type.page_drops_type.page_drop_list").msgclass
