# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pfe_ifl_oc.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x10pfe_ifl_oc.proto\x1a\x13telemetry_top.proto\"\xc5\x05\n\x12interfaces_pfe_ifl\x12\x36\n\tinterface\x18\x97\x01 \x03(\x0b\x32\".interfaces_pfe_ifl.interface_list\x1a\xf6\x04\n\x0einterface_list\x12M\n\rsubinterfaces\x18\x97\x01 \x01(\x0b\x32\x35.interfaces_pfe_ifl.interface_list.subinterfaces_type\x1a\x94\x04\n\x12subinterfaces_type\x12]\n\x0csubinterface\x18\x33 \x03(\x0b\x32G.interfaces_pfe_ifl.interface_list.subinterfaces_type.subinterface_list\x1a\x9e\x03\n\x11subinterface_list\x12\x62\n\x05state\x18\x97\x01 \x01(\x0b\x32R.interfaces_pfe_ifl.interface_list.subinterfaces_type.subinterface_list.state_type\x1a\xa4\x02\n\nstate_type\x12s\n\x08\x63ounters\x18\x97\x01 \x01(\x0b\x32`.interfaces_pfe_ifl.interface_list.subinterfaces_type.subinterface_list.state_type.counters_type\x1a\xa0\x01\n\rcounters_type\x12\x11\n\tin_octets\x18\x33 \x01(\x04\x12\x17\n\x0fin_unicast_pkts\x18\x34 \x01(\x04\x12\x19\n\x11in_multicast_pkts\x18\x36 \x01(\x04\x12\x12\n\nout_octets\x18: \x01(\x04\x12\x18\n\x10out_unicast_pkts\x18; \x01(\x04\x12\x1a\n\x12out_multicast_pkts\x18= \x01(\x04:Q\n\x1bjnpr_interfaces_pfe_ifl_ext\x12\x17.JuniperNetworksSensors\x18: \x01(\x0b\x32\x13.interfaces_pfe_ifl"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

Interfaces_pfe_ifl = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_pfe_ifl").msgclass
Interfaces_pfe_ifl::Interface_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_pfe_ifl.interface_list").msgclass
Interfaces_pfe_ifl::Interface_list::Subinterfaces_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_pfe_ifl.interface_list.subinterfaces_type").msgclass
Interfaces_pfe_ifl::Interface_list::Subinterfaces_type::Subinterface_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_pfe_ifl.interface_list.subinterfaces_type.subinterface_list").msgclass
Interfaces_pfe_ifl::Interface_list::Subinterfaces_type::Subinterface_list::State_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_pfe_ifl.interface_list.subinterfaces_type.subinterface_list.state_type").msgclass
Interfaces_pfe_ifl::Interface_list::Subinterfaces_type::Subinterface_list::State_type::Counters_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_pfe_ifl.interface_list.subinterfaces_type.subinterface_list.state_type.counters_type").msgclass
