# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pfe_iflset_qstats.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x17pfe_iflset_qstats.proto\x1a\x13telemetry_top.proto\"\x8e\x08\n\x14junos_pfe_iflset_234\x12\x32\n\x06system\x18\x97\x01 \x01(\x0b\x32!.junos_pfe_iflset_234.system_type\x1a\xc1\x07\n\x0bsystem_type\x12\x42\n\x08linecard\x18\x97\x01 \x01(\x0b\x32/.junos_pfe_iflset_234.system_type.linecard_type\x1a\xed\x06\n\rlinecard_type\x12\x46\n\x03\x63os\x18\x97\x01 \x01(\x0b\x32\x38.junos_pfe_iflset_234.system_type.linecard_type.cos_type\x1a\x93\x06\n\x08\x63os_type\x12[\n\tinterface\x18\x97\x01 \x03(\x0b\x32G.junos_pfe_iflset_234.system_type.linecard_type.cos_type.interface_list\x1a\xa9\x05\n\x0einterface_list\x12\x13\n\x04name\x18\x33 \x01(\tB\x05\x82@\x02\x08\x01\x12r\n\rinterface_set\x18\x97\x01 \x03(\x0b\x32Z.junos_pfe_iflset_234.system_type.linecard_type.cos_type.interface_list.interface_set_list\x1a\x8d\x04\n\x12interface_set_list\x12\x1a\n\x0biflsetindex\x18\x33 \x01(\x04\x42\x05\x82@\x02\x08\x01\x12w\n\x06output\x18\x97\x01 \x01(\x0b\x32\x66.junos_pfe_iflset_234.system_type.linecard_type.cos_type.interface_list.interface_set_list.output_type\x1a\xe1\x02\n\x0boutput_type\x12\x81\x01\n\x05queue\x18\x97\x01 \x03(\x0b\x32q.junos_pfe_iflset_234.system_type.linecard_type.cos_type.interface_list.interface_set_list.output_type.queue_list\x1a\xcd\x01\n\nqueue_list\x12\x1b\n\x0cqueue_number\x18\x33 \x01(\x04\x42\x05\x82@\x02\x08\x01\x12\x13\n\x0bqueued_pkts\x18\x34 \x01(\x04\x12\x15\n\rqueued_octets\x18\x35 \x01(\x04\x12\x15\n\rtransmit_pkts\x18\x36 \x01(\x04\x12\x17\n\x0ftransmit_octets\x18\x37 \x01(\x04\x12\x16\n\x0etail_drop_pkts\x18\x38 \x01(\x04\x12\x15\n\rred_drop_pkts\x18\x39 \x01(\x04\x12\x17\n\x0fred_drop_octets\x18: \x01(\x04:V\n\x1djnpr_junos_pfe_iflset_234_ext\x12\x17.JuniperNetworksSensors\x18\xea\x01 \x01(\x0b\x32\x15.junos_pfe_iflset_234"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

Junos_pfe_iflset_234 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_pfe_iflset_234").msgclass
Junos_pfe_iflset_234::System_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_pfe_iflset_234.system_type").msgclass
Junos_pfe_iflset_234::System_type::Linecard_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_pfe_iflset_234.system_type.linecard_type").msgclass
Junos_pfe_iflset_234::System_type::Linecard_type::Cos_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_pfe_iflset_234.system_type.linecard_type.cos_type").msgclass
Junos_pfe_iflset_234::System_type::Linecard_type::Cos_type::Interface_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_pfe_iflset_234.system_type.linecard_type.cos_type.interface_list").msgclass
Junos_pfe_iflset_234::System_type::Linecard_type::Cos_type::Interface_list::Interface_set_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_pfe_iflset_234.system_type.linecard_type.cos_type.interface_list.interface_set_list").msgclass
Junos_pfe_iflset_234::System_type::Linecard_type::Cos_type::Interface_list::Interface_set_list::Output_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_pfe_iflset_234.system_type.linecard_type.cos_type.interface_list.interface_set_list.output_type").msgclass
Junos_pfe_iflset_234::System_type::Linecard_type::Cos_type::Interface_list::Interface_set_list::Output_type::Queue_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_pfe_iflset_234.system_type.linecard_type.cos_type.interface_list.interface_set_list.output_type.queue_list").msgclass
