# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pfe_per_prefix_v6_stats.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x1dpfe_per_prefix_v6_stats.proto\x1a\x13telemetry_top.proto\"\x86\x06\n#network_instances_pfe_per_prefix_v6\x12U\n\x10network_instance\x18\xcd\x01 \x03(\x0b\x32:.network_instances_pfe_per_prefix_v6.network_instance_list\x1a\x87\x05\n\x15network_instance_list\x12\x14\n\x04name\x18\xce\x01 \x01(\tB\x05\x82@\x02\x08\x01\x12S\n\x04\x61\x66ts\x18\xcd\x01 \x01(\x0b\x32\x44.network_instances_pfe_per_prefix_v6.network_instance_list.afts_type\x1a\x82\x04\n\tafts_type\x12m\n\x0cipv6_unicast\x18\xcd\x01 \x01(\x0b\x32V.network_instances_pfe_per_prefix_v6.network_instance_list.afts_type.ipv6_unicast_type\x1a\x85\x03\n\x11ipv6_unicast_type\x12{\n\nipv6_entry\x18\xcd\x01 \x03(\x0b\x32\x66.network_instances_pfe_per_prefix_v6.network_instance_list.afts_type.ipv6_unicast_type.ipv6_entry_list\x1a\xf2\x01\n\x0fipv6_entry_list\x12\x16\n\x06prefix\x18\xcf\x01 \x01(\tB\x05\x82@\x02\x08\x01\x12\x81\x01\n\x05state\x18\xcd\x01 \x01(\x0b\x32q.network_instances_pfe_per_prefix_v6.network_instance_list.afts_type.ipv6_unicast_type.ipv6_entry_list.state_type\x1a\x43\n\nstate_type\x12\x1a\n\x11packets_forwarded\x18\xd0\x01 \x01(\x04\x12\x19\n\x10octets_forwarded\x18\xd1\x01 \x01(\x04:t\n,jnpr_network_instances_pfe_per_prefix_v6_ext\x12\x17.JuniperNetworksSensors\x18\x90\x01 \x01(\x0b\x32$.network_instances_pfe_per_prefix_v6"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

Network_instances_pfe_per_prefix_v6 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("network_instances_pfe_per_prefix_v6").msgclass
Network_instances_pfe_per_prefix_v6::Network_instance_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("network_instances_pfe_per_prefix_v6.network_instance_list").msgclass
Network_instances_pfe_per_prefix_v6::Network_instance_list::Afts_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("network_instances_pfe_per_prefix_v6.network_instance_list.afts_type").msgclass
Network_instances_pfe_per_prefix_v6::Network_instance_list::Afts_type::Ipv6_unicast_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("network_instances_pfe_per_prefix_v6.network_instance_list.afts_type.ipv6_unicast_type").msgclass
Network_instances_pfe_per_prefix_v6::Network_instance_list::Afts_type::Ipv6_unicast_type::Ipv6_entry_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("network_instances_pfe_per_prefix_v6.network_instance_list.afts_type.ipv6_unicast_type.ipv6_entry_list").msgclass
Network_instances_pfe_per_prefix_v6::Network_instance_list::Afts_type::Ipv6_unicast_type::Ipv6_entry_list::State_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("network_instances_pfe_per_prefix_v6.network_instance_list.afts_type.ipv6_unicast_type.ipv6_entry_list.state_type").msgclass
