# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pfe_port_qstats_ext.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x19pfe_port_qstats_ext.proto\x1a\x13telemetry_top.proto\"\xbb\x04\n\x1ainterfaces_pfe_port_qstats\x12>\n\tinterface\x18\x97\x01 \x03(\x0b\x32*.interfaces_pfe_port_qstats.interface_list\x1a\xdc\x03\n\x0einterface_list\x12\x13\n\x04name\x18\x33 \x01(\tB\x05\x82@\x02\x08\x01\x12\x45\n\x05state\x18\x97\x01 \x01(\x0b\x32\x35.interfaces_pfe_port_qstats.interface_list.state_type\x1a\xed\x02\n\nstate_type\x12V\n\x08\x63ounters\x18\x97\x01 \x01(\x0b\x32\x43.interfaces_pfe_port_qstats.interface_list.state_type.counters_type\x1a\x86\x02\n\rcounters_type\x12\x66\n\tout_queue\x18\x97\x01 \x03(\x0b\x32R.interfaces_pfe_port_qstats.interface_list.state_type.counters_type.out_queue_list\x1a\x8c\x01\n\x0eout_queue_list\x12\x1b\n\x0cqueue_number\x18\x33 \x01(\rB\x05\x82@\x02\x08\x01\x12\x13\n\x0bqueued_pkts\x18\x34 \x01(\x04\x12\x14\n\x0cqueued_bytes\x18\x35 \x01(\x04\x12\x18\n\x10lp_red_drop_pkts\x18\x36 \x01(\x04\x12\x18\n\x10hp_red_drop_pkts\x18\x37 \x01(\x04:b\n#jnpr_interfaces_pfe_port_qstats_ext\x12\x17.JuniperNetworksSensors\x18\x85\x01 \x01(\x0b\x32\x1b.interfaces_pfe_port_qstats"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

Interfaces_pfe_port_qstats = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_pfe_port_qstats").msgclass
Interfaces_pfe_port_qstats::Interface_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_pfe_port_qstats.interface_list").msgclass
Interfaces_pfe_port_qstats::Interface_list::State_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_pfe_port_qstats.interface_list.state_type").msgclass
Interfaces_pfe_port_qstats::Interface_list::State_type::Counters_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_pfe_port_qstats.interface_list.state_type.counters_type").msgclass
Interfaces_pfe_port_qstats::Interface_list::State_type::Counters_type::Out_queue_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("interfaces_pfe_port_qstats.interface_list.state_type.counters_type.out_queue_list").msgclass
