# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qmon.proto

require 'google/protobuf'

require 'pbj_pb'
require 'telemetry_top_pb'


descriptor_data = "\n\nqmon.proto\x1a\tpbj.proto\x1a\x13telemetry_top.proto\"P\n\x0cQueueMonitor\x12@\n\x1aqueue_monitor_element_info\x18\x01 \x03(\x0b\x32\x14.QueueMonitorElementB\x06\xe2?\x03\x10\x80\x10\"\xca\x01\n\x13QueueMonitorElement\x12\x1b\n\x07if_name\x18\x01 \x02(\tB\n\xe2?\x02\x18\x04\x82@\x02\x08\x01\x12\x1d\n\x0eparent_ae_name\x18\x02 \x01(\tB\x05\xe2?\x02\x18\x04\x12;\n\x1bqueue_monitor_stats_ingress\x18\x03 \x01(\x0b\x32\x16.QueueMonitorDirection\x12:\n\x1aqueue_monitor_stats_egress\x18\x04 \x01(\x0b\x32\x16.QueueMonitorDirection\"T\n\x15QueueMonitorDirection\x12;\n\x18queue_monitor_stats_info\x18\x01 \x03(\x0b\x32\x12.QueueMonitorStatsB\x05\xe2?\x02\x10\x08\"\xd9\x04\n\x11QueueMonitorStats\x12\x1b\n\x0cqueue_number\x18\x01 \x02(\rB\x05\x82@\x02\x08\x01\x12\x17\n\x08queue_id\x18\x02 \x02(\rB\x05\x82@\x02\x08\x01\x12*\n\x1bpeak_buffer_occupancy_bytes\x18\x03 \x02(\rB\x05\x82@\x02 \x01\x12,\n\x1dpeak_buffer_occupancy_percent\x18\x04 \x01(\rB\x05\x82@\x02 \x01\x12\x16\n\x07packets\x18\x05 \x02(\x04\x42\x05\x82@\x02\x18\x01\x12\x15\n\x06octets\x18\x06 \x02(\x04\x42\x05\x82@\x02\x18\x01\x12 \n\x11tail_drop_packets\x18\x07 \x02(\x04\x42\x05\x82@\x02\x18\x01\x12\x1f\n\x10tail_drop_octets\x18\x08 \x02(\x04\x42\x05\x82@\x02\x18\x01\x12\'\n\x18red_drop_packets_color_0\x18\t \x02(\x04\x42\x05\x82@\x02\x18\x01\x12&\n\x17red_drop_octets_color_0\x18\n \x02(\x04\x42\x05\x82@\x02\x18\x01\x12\'\n\x18red_drop_packets_color_1\x18\x0b \x02(\x04\x42\x05\x82@\x02\x18\x01\x12&\n\x17red_drop_octets_color_1\x18\x0c \x02(\x04\x42\x05\x82@\x02\x18\x01\x12\'\n\x18red_drop_packets_color_2\x18\r \x02(\x04\x42\x05\x82@\x02\x18\x01\x12&\n\x17red_drop_octets_color_2\x18\x0e \x02(\x04\x42\x05\x82@\x02\x18\x01\x12\'\n\x18red_drop_packets_color_3\x18\x0f \x02(\x04\x42\x05\x82@\x02\x18\x01\x12&\n\x17red_drop_octets_color_3\x18\x10 \x02(\x04\x42\x05\x82@\x02\x18\x01:=\n\rjnpr_qmon_ext\x12\x17.JuniperNetworksSensors\x18\x0f \x01(\x0b\x32\r.QueueMonitor"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

QueueMonitor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QueueMonitor").msgclass
QueueMonitorElement = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QueueMonitorElement").msgclass
QueueMonitorDirection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QueueMonitorDirection").msgclass
QueueMonitorStats = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QueueMonitorStats").msgclass
