# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpd_evpn_global_render.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x1crpd_evpn_global_render.proto\x1a\x13telemetry_top.proto\"\xd3\x04\n\njunos_evpn\x12$\n\x04\x65vpn\x18\xab\x01 \x01(\x0b\x32\x15.junos_evpn.evpn_type\x1a\x9e\x04\n\tevpn_type\x12N\n\x14\x65vpn_smet_forwarding\x18\xab\x01 \x01(\x0b\x32/.junos_evpn.evpn_type.evpn_smet_forwarding_type\x12:\n\nl3_context\x18\xb4\x01 \x03(\x0b\x32%.junos_evpn.evpn_type.l3_context_list\x1aZ\n\x19\x65vpn_smet_forwarding_type\x12\x0f\n\x07\x65nabled\x18G \x01(\x08\x12\x15\n\rnexthop_limit\x18H \x01(\r\x12\x15\n\rnexthop_usage\x18I \x01(\r\x1a\xa8\x02\n\x0fl3_context_list\x12\x1b\n\x0c\x63ontext_name\x18G \x01(\tB\x05\x82@\x02\x08\x01\x12\x15\n\rencapsulation\x18H \x01(\t\x12\x1a\n\x12\x61\x64vertisement_mode\x18I \x01(\t\x12\x1e\n\x16multicast_routing_mode\x18J \x01(\t\x12Z\n\x12ip_prefix_database\x18\xaa\x01 \x03(\x0b\x32=.junos_evpn.evpn_type.l3_context_list.ip_prefix_database_list\x1aI\n\x17ip_prefix_database_list\x12\x18\n\tip_prefix\x18G \x01(\tB\x05\x82@\x02\x08\x01\x12\x14\n\x0croute_status\x18H \x01(\t:A\n\x13jnpr_junos_evpn_ext\x12\x17.JuniperNetworksSensors\x18q \x01(\x0b\x32\x0b.junos_evpn"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

Junos_evpn = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_evpn").msgclass
Junos_evpn::Evpn_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_evpn.evpn_type").msgclass
Junos_evpn::Evpn_type::Evpn_smet_forwarding_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_evpn.evpn_type.evpn_smet_forwarding_type").msgclass
Junos_evpn::Evpn_type::L3_context_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_evpn.evpn_type.l3_context_list").msgclass
Junos_evpn::Evpn_type::L3_context_list::Ip_prefix_database_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_evpn.evpn_type.l3_context_list.ip_prefix_database_list").msgclass
