# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spu_cpu_util.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n\x12spu_cpu_util.proto\x1a\x13telemetry_top.proto\"\xae\x02\n\x11junos_pfe_spu_cpu\x12\x33\n\x08security\x18\x97\x01 \x01(\x0b\x32 .junos_pfe_spu_cpu.security_type\x1a\xe3\x01\n\rsecurity_type\x12\x37\n\x03spu\x18\x97\x01 \x01(\x0b\x32).junos_pfe_spu_cpu.security_type.spu_type\x1a\x98\x01\n\x08spu_type\x12\x10\n\x08spu_name\x18\x33 \x01(\t\x12@\n\x03\x63pu\x18\x97\x01 \x03(\x0b\x32\x32.junos_pfe_spu_cpu.security_type.spu_type.cpu_list\x1a\x38\n\x08\x63pu_list\x12\x17\n\x08\x63pu_name\x18\x34 \x01(\tB\x05\x82@\x02\x08\x01\x12\x13\n\x0butilization\x18\x35 \x01(\r:P\n\x1ajnpr_junos_pfe_spu_cpu_ext\x12\x17.JuniperNetworksSensors\x18\x82\x01 \x01(\x0b\x32\x12.junos_pfe_spu_cpu"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

Junos_pfe_spu_cpu = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_pfe_spu_cpu").msgclass
Junos_pfe_spu_cpu::Security_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_pfe_spu_cpu.security_type").msgclass
Junos_pfe_spu_cpu::Security_type::Spu_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_pfe_spu_cpu.security_type.spu_type").msgclass
Junos_pfe_spu_cpu::Security_type::Spu_type::Cpu_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("junos_pfe_spu_cpu.security_type.spu_type.cpu_list").msgclass
