# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sr_te_per_lsp_transit_stats.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n!sr_te_per_lsp_transit_stats.proto\x1a\x13telemetry_top.proto\"\xd4\x08\n\x1bmpls_SrTePerLspTransitStats\x12S\n\x13signaling_protocols\x18\x97\x01 \x01(\x0b\x32\x35.mpls_SrTePerLspTransitStats.signaling_protocols_type\x1a\xdf\x07\n\x18signaling_protocols_type\x12\x64\n\x0fsegment_routing\x18\x97\x01 \x01(\x0b\x32J.mpls_SrTePerLspTransitStats.signaling_protocols_type.segment_routing_type\x1a\xdc\x06\n\x14segment_routing_type\x12\x97\x01\n\x1esr_te_per_lsp_transit_policies\x18\x97\x01 \x01(\x0b\x32n.mpls_SrTePerLspTransitStats.signaling_protocols_type.segment_routing_type.sr_te_per_lsp_transit_policies_type\x1a\xa9\x05\n#sr_te_per_lsp_transit_policies_type\x12\xb8\x01\n\x1csr_te_per_lsp_transit_policy\x18\x97\x01 \x03(\x0b\x32\x90\x01.mpls_SrTePerLspTransitStats.signaling_protocols_type.segment_routing_type.sr_te_per_lsp_transit_policies_type.sr_te_per_lsp_transit_policy_list\x1a\xc6\x03\n!sr_te_per_lsp_transit_policy_list\x12\xae\x01\n\x06record\x18\x97\x01 \x03(\x0b\x32\x9c\x01.mpls_SrTePerLspTransitStats.signaling_protocols_type.segment_routing_type.sr_te_per_lsp_transit_policies_type.sr_te_per_lsp_transit_policy_list.record_list\x1a\xef\x01\n\x0brecord_list\x12\x1a\n\x0btunnel_name\x18\x33 \x01(\tB\x05\x82@\x02\x08\x01\x12\x15\n\x06source\x18\x34 \x01(\tB\x05\x82@\x02\x08\x01\x12\x15\n\x06origin\x18\x35 \x01(\tB\x05\x82@\x02\x08\x01\x12\x1c\n\rdistinguisher\x18\x36 \x01(\tB\x05\x82@\x02\x08\x01\x12\x17\n\x08lsp_name\x18\x37 \x01(\tB\x05\x82@\x02\x08\x01\x12\x14\n\x0c\x63ounter_name\x18\x38 \x01(\t\x12\x1b\n\x13instance_identifier\x18\x39 \x01(\r\x12\x16\n\x07packets\x18: \x01(\x04\x42\x05\x82@\x02\x18\x01\x12\x14\n\x05\x62ytes\x18; \x01(\x04\x42\x05\x82@\x02\x18\x01:c\n$jnpr_mpls_SrTePerLspTransitStats_ext\x12\x17.JuniperNetworksSensors\x18h \x01(\x0b\x32\x1c.mpls_SrTePerLspTransitStats"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

Mpls_SrTePerLspTransitStats = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mpls_SrTePerLspTransitStats").msgclass
Mpls_SrTePerLspTransitStats::Signaling_protocols_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mpls_SrTePerLspTransitStats.signaling_protocols_type").msgclass
Mpls_SrTePerLspTransitStats::Signaling_protocols_type::Segment_routing_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mpls_SrTePerLspTransitStats.signaling_protocols_type.segment_routing_type").msgclass
Mpls_SrTePerLspTransitStats::Signaling_protocols_type::Segment_routing_type::Sr_te_per_lsp_transit_policies_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mpls_SrTePerLspTransitStats.signaling_protocols_type.segment_routing_type.sr_te_per_lsp_transit_policies_type").msgclass
Mpls_SrTePerLspTransitStats::Signaling_protocols_type::Segment_routing_type::Sr_te_per_lsp_transit_policies_type::Sr_te_per_lsp_transit_policy_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mpls_SrTePerLspTransitStats.signaling_protocols_type.segment_routing_type.sr_te_per_lsp_transit_policies_type.sr_te_per_lsp_transit_policy_list").msgclass
Mpls_SrTePerLspTransitStats::Signaling_protocols_type::Segment_routing_type::Sr_te_per_lsp_transit_policies_type::Sr_te_per_lsp_transit_policy_list::Record_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mpls_SrTePerLspTransitStats.signaling_protocols_type.segment_routing_type.sr_te_per_lsp_transit_policies_type.sr_te_per_lsp_transit_policy_list.record_list").msgclass
