# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telemetry_top.proto

require 'google/protobuf'

require 'google/protobuf/descriptor_pb'


descriptor_data = "\n\x13telemetry_top.proto\x1a google/protobuf/descriptor.proto\"\xa4\x01\n\x15TelemetryFieldOptions\x12\x0e\n\x06is_key\x18\x01 \x01(\x08\x12\x14\n\x0cis_timestamp\x18\x02 \x01(\x08\x12\x12\n\nis_counter\x18\x03 \x01(\x08\x12\x10\n\x08is_gauge\x18\x04 \x01(\x08\x12\x13\n\x0bis_instance\x18\x05 \x01(\x08\x12\x14\n\x0cis_gauge_min\x18\x06 \x01(\x08\x12\x14\n\x0cis_gauge_max\x18\x07 \x01(\x08\"\xb7\x02\n\x0fTelemetryStream\x12\x18\n\tsystem_id\x18\x01 \x02(\tB\x05\x82@\x02\x08\x01\x12\x1b\n\x0c\x63omponent_id\x18\x02 \x01(\rB\x05\x82@\x02\x08\x01\x12\x1f\n\x10sub_component_id\x18\x03 \x01(\rB\x05\x82@\x02\x08\x01\x12\x1a\n\x0bsensor_name\x18\x04 \x01(\tB\x05\x82@\x02\x08\x01\x12\x17\n\x0fsequence_number\x18\x05 \x01(\r\x12\x18\n\ttimestamp\x18\x06 \x01(\x04\x42\x05\x82@\x02\x10\x01\x12\x15\n\rversion_major\x18\x07 \x01(\r\x12\x15\n\rversion_minor\x18\x08 \x01(\r\x12\x0b\n\x03\x65om\x18\t \x01(\x08\x12\x1a\n\x04ietf\x18\x64 \x01(\x0b\x32\x0c.IETFSensors\x12&\n\nenterprise\x18\x65 \x01(\x0b\x32\x12.EnterpriseSensors\"\x17\n\x0bIETFSensors*\x08\x08\x01\x10\x80\x80\x80\x80\x02\"\x1d\n\x11\x45nterpriseSensors*\x08\x08\x01\x10\x80\x80\x80\x80\x02\"\"\n\x16JuniperNetworksSensors*\x08\x08\x01\x10\x80\x80\x80\x80\x02:Q\n\x11telemetry_options\x12\x1d.google.protobuf.FieldOptions\x18\x80\x08 \x01(\x0b\x32\x16.TelemetryFieldOptions:E\n\x0fjuniperNetworks\x12\x12.EnterpriseSensors\x18\xcc\x14 \x01(\x0b\x32\x17.JuniperNetworksSensors"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

TelemetryFieldOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TelemetryFieldOptions").msgclass
TelemetryStream = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("TelemetryStream").msgclass
IETFSensors = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IETFSensors").msgclass
EnterpriseSensors = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("EnterpriseSensors").msgclass
JuniperNetworksSensors = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("JuniperNetworksSensors").msgclass
