# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xmlproxyd-junos-openconfig-system-render.proto

require 'google/protobuf'

require 'telemetry_top_pb'


descriptor_data = "\n.xmlproxyd-junos-openconfig-system-render.proto\x1a\x13telemetry_top.proto\"\xa0\x07\n\x11system_system_250\x12\x37\n\nssh_server\x18\x99\x01 \x01(\x0b\x32\".system_system_250.ssh_server_type\x12=\n\rtelnet_server\x18\x9a\x01 \x01(\x0b\x32%.system_system_250.telnet_server_type\x12)\n\x03\x61\x61\x61\x18\x9c\x01 \x01(\x0b\x32\x1b.system_system_250.aaa_type\x1a\x89\x01\n\x0fssh_server_type\x12=\n\x05state\x18\x97\x01 \x01(\x0b\x32-.system_system_250.ssh_server_type.state_type\x1a\x37\n\nstate_type\x12\x12\n\nrate_limit\x18\x36 \x01(\r\x12\x15\n\rsession_limit\x18\x37 \x01(\r\x1a\x9f\x01\n\x12telnet_server_type\x12@\n\x05state\x18\x97\x01 \x01(\x0b\x32\x30.system_system_250.telnet_server_type.state_type\x1aG\n\nstate_type\x12\x0e\n\x06\x65nable\x18\x33 \x01(\x08\x12\x12\n\nrate_limit\x18\x34 \x01(\r\x12\x15\n\rsession_limit\x18\x35 \x01(\r\x1a\xb9\x03\n\x08\x61\x61\x61_type\x12@\n\naccounting\x18\x98\x01 \x01(\x0b\x32+.system_system_250.aaa_type.accounting_type\x1a\xea\x02\n\x0f\x61\x63\x63ounting_type\x12H\n\x06\x65vents\x18\x98\x01 \x01(\x0b\x32\x37.system_system_250.aaa_type.accounting_type.events_type\x1a\x8c\x02\n\x0b\x65vents_type\x12R\n\x05\x65vent\x18\x97\x01 \x03(\x0b\x32\x42.system_system_250.aaa_type.accounting_type.events_type.event_list\x1a\xa8\x01\n\nevent_list\x12\x19\n\nevent_type\x18\x33 \x01(\tB\x05\x82@\x02\x08\x01\x12]\n\x05state\x18\x97\x01 \x01(\x0b\x32M.system_system_250.aaa_type.accounting_type.events_type.event_list.state_type\x1a \n\nstate_type\x12\x12\n\nevent_type\x18\x33 \x01(\t:P\n\x1ajnpr_system_system_250_ext\x12\x17.JuniperNetworksSensors\x18\xfa\x01 \x01(\x0b\x32\x12.system_system_250"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

System_system_250 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_system_250").msgclass
System_system_250::Ssh_server_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_system_250.ssh_server_type").msgclass
System_system_250::Ssh_server_type::State_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_system_250.ssh_server_type.state_type").msgclass
System_system_250::Telnet_server_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_system_250.telnet_server_type").msgclass
System_system_250::Telnet_server_type::State_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_system_250.telnet_server_type.state_type").msgclass
System_system_250::Aaa_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_system_250.aaa_type").msgclass
System_system_250::Aaa_type::Accounting_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_system_250.aaa_type.accounting_type").msgclass
System_system_250::Aaa_type::Accounting_type::Events_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_system_250.aaa_type.accounting_type.events_type").msgclass
System_system_250::Aaa_type::Accounting_type::Events_type::Event_list = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_system_250.aaa_type.accounting_type.events_type.event_list").msgclass
System_system_250::Aaa_type::Accounting_type::Events_type::Event_list::State_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("system_system_250.aaa_type.accounting_type.events_type.event_list.state_type").msgclass
